version: '3.8'

services:
  user-service:
    build: ./user-service/
    container_name: user-service
    ports:
    - "8001:8000"

  order-service:
    build: ./order-service/
    container_name: order-service
    ports:
    - "8002:8000"
